---
layout: blog
categories: C++
title: Item 8：阻止析构函数抛出异常
subtitle: Effective C++ 读书笔记
tags: C++ 异常
excerpt: 阻止析构函数抛出异常
---

> Prevent exceptions from leaving destructors

C++不会禁止析构函数抛出异常，却也不鼓励你这样做。特别是在多个异常存在的情况下，程序会终止运行或者抛出不明确行为。

但有时候，如果你的析构函数所执行的动作确实有可能在失败时抛出异常，该怎么办呢？比方说如下连接数据库的类，

```cpp
class DBConnection {
public:
    ...
    static DBConnection create();           //function to return DBConnection object;
                                            //params omitted for simplicity

    void close();                           //close connection;
                                            //throw an exception if closing fails
};
```

为了确保DBConnection对象不会忘记调用close函数，我们可以采用资源管理类，并在析构函数中调用关闭数据库连接。如下，

```cpp
class DBConn {
public:
    ...
    ~DBConn() {                             //make sure database connections
        db.close();                         //are always closed
    }

private:
    DBConnection db;
};
```

然后我们可以这样使用DBConn类，

```cpp
{                                           //open a block
    
    DBConn dbc(DBConnection::create());     //create DBConnection object
                                            //and turn it over to a DBConn
                                            //object to manage

    ...                                     //use the DBConnection object
                                            //via the DBConn interface

}                                           //at end of block, the DBConn
                                            //object is destroyed, thus
                                            //automatically calling close on
                                            //the DBConnection object
```

然而DBConn的析构函数有可能会抛出异常，从而导致未定义的行为。
解决方法一般有如下两种，

* 调用abort来终止程序，如下，

```cpp
DBConn::~DBConn() {
    try { db.close(); }
    catch (...) {
        make log entry that the call to close failed;
        std::abort();
    }
}
```

* 吞下异常，将异常记录在日志中。

这两种方法各有优劣，终止程序可以防止未定义行为的出现，吞下异常可以保证程序继续可靠的运行。
一个较好的策略是重新设计DBConn的接口，使得它能够应对可能出现的异常。

```cpp
class DBConn {
public:
    ...
    void close() {                          //new function for client use
        db.close();
        closed = true;
    }

    ~DBConn() {
        if (!closed) {
            try {                           //close the connection
                db.close();                 //if the client didn't
            }
            catch (...) {                   //if closing fails, terminate or swallow
                make log entry that call to close failed;
                ...
            }
        }
    }

private:
    DBConnection db;
    bool closed;
};
```

这种设计也并非能完全解决上面出现的问题，在第一次关闭连接失败后，我们仍面临着终止程序运行或吞下异常的抉择。
庆幸的是，它还多给了我们一次解决问题的机会。
